export const spanishQuestions = {
    "Translate 'Me llamo' To English": "My name is",
    "Translate 'Hola, soy Markus' To English": "Hi, I'm Markus",
    "Translate '¿Cómo te llamas?' To English": "What is your name?",
    "Translate '(Yo) tengo … años' To English": "I am … years old.",
    "Translate '(Yo) soy de' To English…": "I come from…",
    "Translate 'Buenos día' To Englishs": "Good morning",
    "Translate 'Buenas tardes' To English": "Good afternoon",
    "Translate 'Buenas noches' To English": "Good evening / Good night",
    "Translate '¿Cómo está usted' To English?": "How are you? (formal)",
    "Translate '¿Cómo estás?' To English": "How are you? (informal)",
    "Translate '¿Qué tal?' To English": "How are you? (informal) / What's up?",
    "Translate '¿Cómo te va?' To English": "How's it going?",
    "Translate '¿Qué haces?' To English": "What are you doing?",
    "Translate '¿Qué pasa' To English?": "What's happening?",
    "Translate 'Bien, gracias' To English": "Good, thank you",
    "Translate 'Muy bie' To Englishn": "Very well",
    "Translate 'Así, así' To English": "So, so",
    "Translate 'Como siempr' To Englishe": "As always",
    "Translate '¿Y tú' To English?": "And you?",
    "Translate '¡Gracias!' To English": "Thank you!",
    "Translate '¡Muchas gracias!' To English": "Thank you very much!",
    "Translate '¡De nada!' To English": "You're welcome! / No problem!",
    "Translate 'Por favo' To Englishr": "Please",
    "Translate '¡Perdon!' To English": "Excuse me!",
    "Translate '¡Disculpe' To English!": "Excuse me!",
    "Translate '¡Lo siento!' To English": "Sorry! ",
    "Translate '¿Qué…?' To English": "What?",
    "Translate '¿Quién…?' To English": "Who?",
    "Translate '¿Cuándo…?' To English": "When?",
    "Translate '¿Dónde…' To English?": "¿Dónde…?",
    "Translate '¿Por qué…' To English?": "Why?",
    "Translate '¿Cuál?' To English": "Which?",
    "Translate '¿Cómo…?' To English": "How?",
    "Translate '¿Qué hora tienes?' To English": "What time is it?",
    "Translate '¿De dónde viene' To English?": "Where are you from?",
    "Translate '¿Dónde vives?' To English": "Where do you live?",
    "Translate '¿Puede ayudarme?' To English": "Can you help me?",
    "Translate '¿Podría ayudarle?' To English": "Can I help you?",
    "Translate '¿Cuánto cuesta eso' To English?": "How much does it cost?",
    "Translate '¿Entiende?' To English": "Do you understand?",
    "Translate '¡Puede repetirlo' To English!": "Can you say that again?",
    "Translate '¿Qué significa [word]' To English?": "What does [word] mean?",
    "Translate '¿Puedes hablar más despacio' To English?": "Can you speak slowly?",
    "Translate '¿Dónde puedo encontrar un taxi' To English?": "Where can I find a taxi?",
    "Translate '¿Dónde está [hotel's name] hotel' To English?": "Where is [hotel's name] hotel?",
    "Translate 'Sí' To English": "Yes",
    "Translate 'N' To Englisho": "No ",
    "Translate 'Tal vez' To English": "Maybe",
    "Translate 'Clar' To Englisho": "Of course",
    }